/**
 * \file
 *
 * \brief OPAMP related functionality declaration.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

#ifndef OPAMP_H_INCLUDED
#define OPAMP_H_INCLUDED

#include <compiler.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OPAMP_TIMEBASE_VALUE (3)

int8_t OPERATIONAL_AMPLIFIER_0_init();

void OPERATIONAL_AMPLIFIER_0_EnableSystem();

void OPERATIONAL_AMPLIFIER_0_DisableSystem();

// OP0 API's

void OPERATIONAL_AMPLIFIER_0_SetOP0PositiveInMux(OPAMP_OP0INMUX_MUXPOS_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP0NegativeInMux(OPAMP_OP0INMUX_MUXNEG_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP0TopResMux(OPAMP_OP0RESMUX_MUXTOP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP0BottomResMux(OPAMP_OP0RESMUX_MUXBOT_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP0WiperResMux(OPAMP_OP0RESMUX_MUXWIP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP0SettleTime(uint8_t settleTime);

bool OPERATIONAL_AMPLIFIER_0_IsOP0Settled(void);

void OPERATIONAL_AMPLIFIER_0_SetOP0OffsetCalibration(uint8_t calValue);

// OP1 API's

void OPERATIONAL_AMPLIFIER_0_SetOP1PositiveInMux(OPAMP_OP1INMUX_MUXPOS_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP1NegativeInMux(OPAMP_OP1INMUX_MUXNEG_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP1TopResMux(OPAMP_OP1RESMUX_MUXTOP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP1BottomResMux(OPAMP_OP1RESMUX_MUXBOT_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP1WiperResMux(OPAMP_OP1RESMUX_MUXWIP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP1SettleTime(uint8_t settleTime);

bool OPERATIONAL_AMPLIFIER_0_IsOP1Settled(void);

void OPERATIONAL_AMPLIFIER_0_SetOP1OffsetCalibration(uint8_t calValue);

// OP2 API's

void OPERATIONAL_AMPLIFIER_0_SetOP2PositiveInMux(OPAMP_OP2INMUX_MUXPOS_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP2NegativeInMux(OPAMP_OP2INMUX_MUXNEG_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP2TopResMux(OPAMP_OP2RESMUX_MUXTOP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP2BottomResMux(OPAMP_OP2RESMUX_MUXBOT_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP2WiperResMux(OPAMP_OP2RESMUX_MUXWIP_t value);

void OPERATIONAL_AMPLIFIER_0_SetOP2SettleTime(uint8_t settleTime);

bool OPERATIONAL_AMPLIFIER_0_IsOP2Settled(void);

void OPERATIONAL_AMPLIFIER_0_SetOP2OffsetCalibration(uint8_t calValue);

#ifdef __cplusplus
}
#endif

#endif /* OPAMP_H_INCLUDED */
